---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: package
    image: maven:3.9.9-eclipse-temurin-21
    commands:
      - mvn -e clean package
      - mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
    when:
      branch:
        - main

  - name: prepare-image-layers
    image: maven:3.9.9-eclipse-temurin-21
    commands:
      - mkdir -p target/dependency
      - cd target/dependency
      - jar -xf ../*.jar
  - name: build-image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: rubasace/radarr-downloader
      tags: latest
    when:
      branch:
        - main
trigger:
  event:
    - push
    - promote
---
kind: signature
hmac: 70ad02670170cdc669c200db3e3ba6da650ff1a2268ca471459934c10d902309

...
